# Generated by Django 5.2.5 on 2025-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bilty_number', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_mobile', models.CharField(max_length=20)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adda_for_vehicle', models.CharField(blank=True, max_length=100)),
                ('adda_for_load', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('amcs_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adda_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('staff_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loading_unloading', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fare_type', models.CharField(choices=[('Paid', 'Paid'), ('To Pay', 'To Pay')], default='To Pay', max_length=20)),
                ('pod_status', models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received')], default='Pending', max_length=20)),
                ('bill_status', models.CharField(choices=[('Billed', 'Billed'), ('Unbilled', 'Unbilled')], default='Unbilled', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Pending', max_length=20)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online')], max_length=20)),
                ('cheque_details', models.CharField(blank=True, max_length=100)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receivable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
